version: 0.2

phases:
  install:
    commands:
      - echo Install Commands...
      - npm install
      - ls
  build:
    commands:
      - echo Build command...
      - echo $CODEBUILD_SRC_DIR
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/app.js