version: 0.2

phases:
  install:
    commands:
      - echo Install Commands...
      - npm install
  pre_build:
    commands:
      - echo Prebuild commands...
      -
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - echo Build command...
      - tsc -p .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/app.js