version: 0.2

phases:
  install:
    commands:
      - echo INSTALL Commands ------------------------------------------------
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo PRE BUILD Commands ----------------------------------------------
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo BUILD Commands --------------------------------------------------
      - ls
      - npm install
      - npm run build
      - npm run test
      - zip basic.zip buildspec.yml
      - zip basic.zip package.json
      - zip basic.zip tsconfig.json
      - zip -r basic.zip src
      - ls
  post_build:
    commands:
      - echo POST BUILD Commands ---------------------------------------------
      - echo Build completed on `date`
artifacts:
  files:
    - basic.zip