version: 0.2

phases:
  install:
    commands:
      - echo INSTALL Commands ------------------------------------------------
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo PRE BUILD Commands ----------------------------------------------
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo BUILD Commands --------------------------------------------------
      - ls
      - npm install
      - npm run build
      - npm run test
      - ls
      - zip -r basic.zip node_modules
      - zip -r basic.zip build/app.js
      #- zip -r basic.zip build/test/app.test.js
      #- zip -r basic.zip build/dynamoDb/__test__/dynamoDb.test.js
      #- zip -r basic.zip build/dynamoDb/dynamoDb.js
      - zip -r basic.zip package.json
      - ls
  post_build:
    commands:
      - echo POST BUILD Commands ---------------------------------------------
      - echo Build completed on `date`
artifacts:
  files:
    - basic.zip