version: 0.2

phases:
  install:
    commands:
      - echo INSTALL Commands ------------------------------------------------
      - echo Install Commands...
      - npm install
      - ls
  pre_build:
    commands:
      - echo PRE BUILD Commands ----------------------------------------------
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo BUILD Commands --------------------------------------------------
      - echo Build command...
      - echo $CODEBUILD_SRC_DIR
      - ls
      - echo Running npm run build..
      - npm run build
      - ls
      - mkdir deploy
      - cp * deploy
      - cd deploy
      - ls
      - cd ..
      - zip -r basic.zip deploy
      - ls
  post_build:
    commands:
      - echo POST BUILD Commands ---------------------------------------------
      - echo Build completed on `date`
artifacts:
  files:
    - basic.zip