---
resources:

- name: git
  type: git
  source:
    uri: https://github.com/ehelin/basic.git

- name: deployLocation
  type: cf
  source:
    api: XXXXXXXXX
    username: XXXXXXXXXX
    password: XXXXXXXXXX
    organization: XXXXXXXXXX
    space: dev
    skip_cert_check: false

jobs:
- name: build
  plan:
  - get: git
    trigger: true
  - task: unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node, "7.4.0"}
      inputs:
      - name: git
        path: pre-build-directory
      outputs:
      - name: post-build
        path: post-build-directory
      run:
        path: sh
        args:
           - -exc
           - |
             ls
             cd pre-build-directory
             npm install
             npm test
             echo [All Done!]
  - aggregate:
      - put: deployLocation
        params:
          manifest: post-build-directory/concourse/manifest-dev.yml
          path: post-build-directory/